### ISSUE TITLE
Text Invisibility When Writing an Address

### ISSUE THREAD

**Issue by Syedmujtaba313** [Ninjas-Code-official/Enatega-Food-Delivery-Solution#13]
Issue: Text Invisibility When Writing an Address

Description:
Users have identified a significant issue related to entering addresses within the application. When users attempt to write an address, the text they input is not visible, making it challenging to accurately input location information.

Steps to Reproduce:

Open the application on a compatible device.
Navigate to a section where you need to enter an address, such as during registration or order placement.
Begin typing the address in the provided text field.
Observe the visibility of the text as you type.

Expected Result:
When entering an address, the text should be visible and distinguishable from the background. Users should be able to see and review the characters they are typing as they input the address.

Actual Result:
Users have reported that when typing an address, the text they input is not visible in the text field. This issue makes it challenging to accurately input location information.

Impact:
This issue has a significant negative impact on the user experience, as it hampers the user's ability to input addresses accurately. Accurate address entry is crucial for various application features, including navigation and order deliveries.

![address not visible](https://github.com/Ninjas-Code-official/Enatega-Food-Delivery-Solution/assets/129438771/3174cc8f-d3f2-455f-b24c-8afab2478f6a)

**Comment by theKashif** [comment]
Dear @Syedmujtaba313 ,

I'm thrilled to share that we've successfully addressed the issue related to text visibility when entering an address.

We greatly appreciate your report and your patience throughout the resolution process. Should you encounter any further concerns or have additional feedback, please do not hesitate to get in touch.

Warm regards,
@beKashif 
@Ninjas-Code-official/ninjas-code
