### ISSUE TITLE
Help Page Links Are Not Functioning Properly in the Enatega single-vendor Customer and Rider Apps 

### ISSUE THREAD

**Issue by Sohailqureshi9** [Ninjas-Code-official/Enatega-Food-Delivery-Solution#15]
### Issue: Help Page Links Not Functioning Properly in Customer and Rider App

**Description:**
Both the customer and rider apps are experiencing an issue where the links on the help page are not working as expected. Users are encountering difficulties accessing the information they need from the help section.

**Impact:**
**User Frustration:** Users of both the customer and rider apps may become frustrated when they are unable to access vital information or assistance due to malfunctioning help page links.

**Decreased Efficiency:** The inability to access relevant support or guidance can slow down operations for both customers and riders.

**Steps to Reproduce:**

1. Open the customer or rider app.
2. Navigate to the help or support section.
3. Attempt to click on any of the links provided for guidance or assistance.
4. Observe that the links are not functioning properly, leading to errors, page crashes, or a lack of responsiveness.

**Expected Resolution:**
The links within the help page in both the customer and rider apps should function properly to provide users with the necessary assistance and guidance. It is essential to ensure that users can easily access and utilize the help resources, enhancing the overall user experience. The issue should be investigated and resolved promptly.
![m11 at 16 41 14_fca4c5b4](https://github.com/Ninjas-Code-official/Enatega-Food-Delivery-Solution/assets/134473133/e4540709-ff17-4073-b4a9-a44f6cdd028f)
![W111hatsApp Image 2023-10-11 at 16 41 14_8c30570b](https://github.com/Ninjas-Code-official/Enatega-Food-Delivery-Solution/assets/134473133/efb204fe-dc41-4d77-aad8-1ac93dda85f9)
![WhatsApp Image 2023-10-11 at 16 41 14_c915dcce](https://github.com/Ninjas-Code-official/Enatega-Food-Delivery-Solution/assets/134473133/aacc3c6b-673e-40b4-8a83-3b62f887e571)

**Comment by theKashif** [comment]
Hi @Sohailqureshi9,
I'm happy to inform you that the issue you reported regarding Help page links, has been successfully solved and now links are working properly.

Thank you for bringing this issue to our attention, and we appreciate your patience. If you encounter any further problems or have additional feedback, please don't hesitate to let us know.

Best regards,
@beKashif
@Ninjas-Code-official/ninjas-code
