### ISSUE TITLE
 Orders Placed by Customers Are Not Being Received by the Enatega Single-vendor Rider app.

### ISSUE THREAD

**Issue by Sohailqureshi9** [Ninjas-Code-official/Enatega-Food-Delivery-Solution#16]
### Issue: Orders Placed by Customers Are Not Being Received by the Rider

**Description:**
There is a critical issue within our system where orders placed by customers are not being successfully transmitted to the designated rider for delivery. As a result, customers' orders are not being fulfilled as expected.

**Impact:**
**Customer Discontent**: Customers may experience significant frustration when their orders are not delivered, leading to a poor user experience and potential loss of business.

**Steps to Reproduce:**

1. A customer places an order through our platform.
2. The system should automatically assign the order to an available rider for delivery.
3. Observe that, in some cases, orders are not being received or acknowledged by the assigned rider.

**Expected Resolution:**
It is imperative to resolve this issue promptly to ensure that customer orders are consistently received by the assigned riders. This may involve identifying and addressing any technical glitches or communication breakdowns in the order assignment process, ultimately improving the reliability of our service and customer satisfaction.

![Wh Image 2023-10-11 at 16 52 39_56d682db](https://github.com/Ninjas-Code-official/Enatega-Food-Delivery-Solution/assets/134473133/9dc5e6a0-71ab-437f-b45f-5648365afd67)

**Comment by theKashif** [comment]
Hi @Sohailqureshi9,
I'm happy to inform you that the issue the rider was facing has been successfully solved. Now when the user order and the admin accepts the order the rider can find the order in the New Orders section, and when the admin assign the order the order will be shown in the My Orders section.

Thank you for bringing this issue to our attention, and we appreciate your patience. If you encounter any further problems or have additional feedback, please don't hesitate to let us know.

Best regards,
@beKashif
@Ninjas-Code-official/ninjas-code
