### ISSUE TITLE
 Sales Review Graph Text Not Properly Visible at Enatega Single-vendor admin page.

### ISSUE THREAD

**Issue by Sohailqureshi9** [Ninjas-Code-official/Enatega-Food-Delivery-Solution#17]
### Description:
There is an issue with the sales review graph where the text within the graph is not clearly visible or properly legible, making it difficult for users to interpret the data presented.
### Impact:
**Data Misinterpretation:** Users may struggle to understand the sales data, which can lead to incorrect conclusions and decision-making.

**Reduced Effectiveness:** The inability to read the text within the sales review graph can hinder the effectiveness of the sales analysis.

### Steps to Reproduce:

1. Access the sales review graph within the website.
2. Observe the text labels, numbers, or descriptions within the graph.
3. Notice that the text is not properly visible, whether due to color contrast, font size, or other readability issues.

Expected Resolution:
The sales review graph should be designed or adjusted to ensure that the text within it is clearly visible and easily legible. This may involve improving color contrast, increasing font size, or addressing any other issues that affect the readability of the text. Providing a graph that is easy to interpret will enhance the user experience and aid in better decision-making.
<img width="914" alt="Sc, 2023-10-12 125257" src="https://github.com/Ninjas-Code-official/Enatega-Food-Delivery-Solution/assets/134473133/be74e93b-b267-4987-819d-798f2d26a496">

**Comment by theKashif** [comment]
Hi @Sohailqureshi9,
I'm happy to inform you that the issue you reported about text invisibility in the graph section, has been successfully solved.

Thank you for bringing this issue to our attention, and we appreciate your patience. If you encounter any further problems or have additional feedback, please don't hesitate to let us know.

Best regards,
@beKashif
@Ninjas-Code-official/ninjas-code
