### ISSUE TITLE
Language Translation Not Functioning on Dashboard in Enatega Single-vendor

### ISSUE THREAD

**Issue by Sohailqureshi9** [Ninjas-Code-official/Enatega-Food-Delivery-Solution#18]
### Description:
A significant issue has been identified on dashboard, where language translation features are not working as intended. Users are unable to access the platform in their preferred language, which impacts the overall user experience.

### Impact:
**Language Barriers**: Users who require content in languages other than the default one may face difficulties navigating and using the platform.

**User Experience:** The inability to access content in their preferred language diminishes the user experience, potentially leading to frustration and confusion.

### Steps to Reproduce:

1. Access the dashboard.
2. Attempt to change the language setting to a language other than the default.
3. Observe that the content on the dashboard does not change, remaining in the default language.

### Expected Resolution:
The language translation feature on the dashboard should be thoroughly reviewed and fixed to ensure users can access content in their preferred language. Proper functionality of this feature is crucial for making our platform accessible and user-friendly for a diverse range of users. Addressing this issue is essential for improving the overall user experience.

<img width="902" alt="Sc2023-10-12 123330" src="https://github.com/Ninjas-Code-official/Enatega-Food-Delivery-Solution/assets/134473133/5fff813f-105c-43aa-90e6-4572aa857bb2">

**Comment by theKashif** [comment]
Dear @Sohailqureshi9,

Good news! We fixed the problem with language translation on the dashboard.

Thank you for letting us know about this, and for being patient. If you run into more issues or have feedback, feel free to contact us.

Best regards,
@beKashif
@Ninjas-Code-official/ninjas-code
