### ISSUE TITLE
Text Invisibility in Dark Theme on Enatega Single-vendor Customer App.

### ISSUE THREAD

**Issue by Sohailqureshi9** [Ninjas-Code-official/Enatega-Food-Delivery-Solution#21]
### Description:
A critical issue has been identified in customer app, particularly when using the dark theme. In this theme, some text elements are not properly visible or are difficult to read, hindering the user's ability to access information effectively.

### Impact:
**User Frustration:** Users may experience frustration and difficulties in navigating the app when text is not clearly visible in the dark theme.

**Reduced Usability:** The issue negatively affects the overall usability and user experience, potentially leading to a loss of app engagement.

### Steps to Reproduce:

1. Open the customer app.
2. Switch to the dark theme or ensure that it is the default theme.
3. Navigate to sections or pages containing text.
4. Observe that some text elements are not properly visible due to issues with text color or contrast.

### Expected Resolution:
The customer app should be reviewed and adjusted to ensure that text is clearly visible and legible in the dark theme. This may involve enhancing text color, contrast, or typography choices to make text elements stand out effectively. Addressing this issue is crucial for providing a seamless and user-friendly experience, especially for users who prefer the dark theme.

![IMG-20231017-WA0005](https://github.com/Ninjas-Code-official/Enatega-Food-Delivery-Solution/assets/134473133/2168f167-d2ea-49ee-986f-b92258bbe2da)
![IMG-20231017-WA0006](https://github.com/Ninjas-Code-official/Enatega-Food-Delivery-Solution/assets/134473133/beac82eb-b349-42c9-82da-43bd7d3f66e9)
![IMG-20231017-WA0007](https://github.com/Ninjas-Code-official/Enatega-Food-Delivery-Solution/assets/134473133/15770f31-9a08-4ed1-a71f-12eb50c5364c)
![IMG-20231017-WA0008](https://github.com/Ninjas-Code-official/Enatega-Food-Delivery-Solution/assets/134473133/506fc7f1-41a3-4625-83f4-d3d65d74c345)
![IMG-20231017-WA0009](https://github.com/Ninjas-Code-official/Enatega-Food-Delivery-Solution/assets/134473133/580eb3ef-80e9-472e-85b8-fbb83a2951a2)

**Comment by theKashif** [comment]
Dear @Sohailqureshi9 ,

I'm excited to share that we've resolved the issue concerning text visibility in the dark theme of the Enatega Single-vendor Customer App.

We appreciate your report, and your patience is highly valued. If you come across any more problems or have additional feedback, please don't hesitate to get in touch.

Warm regards,
@beKashif 
@Ninjas-Code-official/ninjas-code
