### ISSUE TITLE
Dark Mode Does Not affect Carts in Enatega Single-vendor Customer App.

### ISSUE THREAD

**Issue by Sohailqureshi9** [Ninjas-Code-official/Enatega-Food-Delivery-Solution#23]
### Description:
A notable issue has been discovered in customer app related to dark mode functionality. When users switch to dark mode, the appearance of the shopping cart, including its icon, text, or background, remains unchanged. This inconsistency affects the visual coherence of the app's interface.

### Impact:
**Inconsistent User Experience:** Users may find it confusing when the appearance of the shopping cart does not match the chosen theme, leading to an inconsistent user experience.

**Aesthetic and Usability Concerns:** In dark mode, the cart's visual elements may not be visually pleasing or may be difficult to identify, impacting user usability.

### Steps to Reproduce:

1. Open the customer app.
2. Enable dark mode or ensure it is the default theme.
3. Locate and observe the shopping cart icon, text, or background elements.
4. Note that these cart elements remain unchanged in appearance, not adapting to the dark theme.

### Expected Resolution:
The customer app should be modified to ensure that the shopping cart's visual elements (icon, text, background) adapt to the chosen theme, whether it's light or dark mode. This includes making the cart visually coherent in both themes to maintain a unified and user-friendly app interface. Addressing this issue is crucial for enhancing the overall user experience, aesthetics, and usability of the application.

![WhatsApp Image 2023-10-17 at 14 30 25_571b31b9](https://github.com/Ninjas-Code-official/Enatega-Food-Delivery-Solution/assets/134473133/61627f22-d803-4fba-9dcf-9044e5efe1c4)
![WhatsApp Image 2023-10-17 at 14 30 56_e559f36f](https://github.com/Ninjas-Code-official/Enatega-Food-Delivery-Solution/assets/134473133/d2855176-beb2-4a71-bde1-936d43667a80)

**Comment by theKashif** [comment]
Dear @Sohailqureshi9 ,

I'm happy to inform you that we've resolved the issue concerning the dark mode not affecting the carts in the Enatega Single-vendor Customer App.

Thank you for raising this concern, and your patience is greatly appreciated. Should you encounter any further issues or have additional feedback, please don't hesitate to get in touch.

Warm regards,
@beKashif 
@Ninjas-Code-official/ninjas-code
