### ISSUE TITLE
Payment Method Text Not Visible in Dark Mode on Enatega Single Vendor Customer App.

### ISSUE THREAD

**Issue by Sohailqureshi9** [Ninjas-Code-official/Enatega-Food-Delivery-Solution#25]
### Description:
A significant issue has been identified in the Enatega Single Vendor Customer App while using dark mode. In dark mode, the payment method text is not visible or is difficult to read, affecting the user's ability to select and manage their preferred payment method.

### Impact:
**User Frustration:** Users may experience frustration when they cannot see or properly read payment method text in dark mode, leading to a poor user experience.

**Usability Impairment:** The issue hinders users' ability to manage their payment options effectively, impacting the app's overall usability.

### Steps to Reproduce:

1. Open the Enatega Single Vendor Customer App.
2. Enable dark mode or ensure it is set as the default theme.
3. Navigate to the payment method selection section.
4. Observe that the payment method text is not clearly visible or readable due to issues with text color or contrast.

### Expected Resolution:
The Enatega Single Vendor Customer App should be reviewed and adjusted to ensure that payment method text is clearly visible and legible in dark mode. This may involve enhancing text color, contrast, or typography choices to make payment method information stand out effectively. Addressing this issue is crucial for providing a seamless and user-friendly experience, particularly for users who prefer dark mode.

![WhatsApp Image 2023-10-18 at 15 02 47_278697bb](https://github.com/Ninjas-Code-official/Enatega-Food-Delivery-Solution/assets/134473133/1a50c776-eb43-4038-854d-424a639f112e)

**Comment by theKashif** [comment]
Hello @Sohailqureshi9 ,

I'm pleased to share that we've fixed the issue where the payment method text was not visible in dark mode on the Enatega Single Vendor Customer App.

Thank you for reporting this issue, and your patience is much appreciated. If you encounter any more problems or have additional feedback, please don't hesitate to reach out.

Best regards,
@beKashif 
@Ninjas-Code-official/ninjas-code
