### ISSUE TITLE
Back Button Not Properly Visible in Dark Mode on Enatega Single Vendor Customer App.

### ISSUE THREAD

**Issue by Sohailqureshi9** [Ninjas-Code-official/Enatega-Food-Delivery-Solution#26]
### 
Description:
A significant issue has been discovered in the Enatega Single Vendor Customer App when dark mode is enabled. In dark mode, the back button is not clearly visible, hindering the user's ability to navigate back to the previous screen or page.

### Impact:
**User Frustration:** Users may become frustrated when they are unable to locate the back button in dark mode, leading to a less user-friendly experience.

**Navigation Difficulty:** The absence of a visible back button can hinder users' ability to navigate the app effectively and easily.

### Steps to Reproduce:

1. Open the Enatega Single Vendor Customer App.
2. Enable dark mode or ensure it is set as the default theme.
3. Navigate to any screen or page where the back button is typically located.
4. Observe that the back button is not properly visible due to issues with color or contrast.

### Expected Resolution:
The Enatega Single Vendor Customer App should be reviewed and adjusted to ensure that the back button is clearly visible and easily distinguishable in dark mode. This may involve enhancing the back button's color, contrast, or design to make it stand out effectively. Addressing this issue is crucial for enhancing the overall user experience and navigation in dark mode.

![WhatsApp Image 2023-10-18 at 15 02 47_934cf1c9](https://github.com/Ninjas-Code-official/Enatega-Food-Delivery-Solution/assets/134473133/bf9ed536-7bf3-437c-b93c-d71b92230f70)

**Comment by theKashif** [comment]
Hello @Sohailqureshi9 ,

I'm delighted to let you know that we've resolved the issue with the back button not being properly visible in dark mode on the Enatega Single Vendor Customer App.

Thank you for bringing this to our attention, and we value your patience. If you encounter any more issues or have additional feedback, please don't hesitate to reach out.

Best regards,
@beKashif 
@Ninjas-Code-official/ninjas-code
