### ISSUE TITLE
Enatega SingleVendor Admin Allowing Negative Values in Discount, Stock, and Price Fields

### ISSUE THREAD

**Issue by Inshirah23** [Ninjas-Code-official/Enatega-Food-Delivery-Solution#28]
**Describe the bug**
I have identified a critical issue in the Enatega SingleVendor Admin system where it currently allows users to input negative values in fields related to discount, stock, price, and potentially other crucial parameters. 

**To Reproduce**
1) Log in to the Enatega SingleVendor Admin system.
2) Navigate to the product management section or any relevant area where discount, stock, or price fields are editable.
3) Attempt to input a negative value in the discount, stock, or price fields.

**Expected behavior**
Log in to the Enatega SingleVendor Admin system.
Navigate to the product management section or any relevant area where discount, stock, or price fields are editable.
Attempt to input a negative value in the discount, stock, or price fields.

**Screenshots**
![image](https://github.com/ninjas-code-official/food-delivery-multivendor/assets/152266796/71a51ffa-cc58-4691-9264-8b4f0f02f07e)

**Desktop:**
 - Browser : chrome
 
**Additional context**
Please investigate and address this issue promptly to ensure the Enatega SingleVendor Admin system maintains a high level of reliability and accuracy in data processing.

Thank you for your attention to this matter.

**Comment by theKashif** [comment]
Hi, @Inshirah23,

Big thanks for spotting a critical issue! We fixed a bug where users could enter negative values for discounts, stock, and prices in Enatega's SingleVendor admin. This could've caused pricing errors, inventory mess-ups, and data corruption. We implemented input checks, improved UI cues, and ran tests to ensure only positive or zero values were accepted. 

@ninjas-code-official/ninjas-code 
@beKashif 

![negative-values-not-alllowed](https://github.com/ninjas-code-official/food-delivery-singlevendor/assets/87254179/5125e251-a01f-40c9-9ecc-1690e36b71e5)
