### ISSUE TITLE
Enatega SingleVendor Admin Allowing Gap in Rider Username and Accepting Negative Values in Phone Number Field

### ISSUE THREAD

**Issue by Inshirah23** [Ninjas-Code-official/Enatega-Food-Delivery-Solution#29]
**Describe the bug**
I have identified two critical issues in the Enatega SingleVendor Admin system within the rider section. Firstly, the system currently allows users to create rider usernames with gaps, potentially leading to confusion and errors. Secondly, the system accepts negative values in the phone number field, which can impact the ability to contact and manage riders effectively.

**To Reproduce**
Issue 1 (Gap in Rider Username):
1. Log in to the Enatega SingleVendor Admin system.
2. Navigate to the rider management section.
3. Create or edit a rider profile.
4. Attempt to set a username with a gap (e.g., "john doe" instead of "johndoe").

Issue 2 (Negative Value in Phone Number Field):
1. Log in to the Enatega SingleVendor Admin system.
2. Navigate to the rider management section.
3. Create or edit a rider profile.
4. Attempt to input a negative value in the phone number field.

**Expected behavior**
Expected Behavior - Issue 1:
The system should validate and restrict users from creating usernames with gaps, ensuring consistency and preventing potential issues with user identification.

Expected Behavior - Issue 1:
The system should validate and restrict users from creating usernames with gaps, ensuring consistency and preventing potential issues with user identification.

**Screenshots**
![image](https://github.com/ninjas-code-official/food-delivery-multivendor/assets/152266796/4e4c8975-0ff2-4e43-b2d3-b644811108e6)

**Desktop:**
  - Browser : chrome

**Additional context**
Please investigate and address these issues promptly to enhance the reliability and functionality of the Enatega SingleVendor Admin system.

Thank you for your attention to these matters.

**Comment by theKashif** [comment]
Hi, @Inshirah23,

Thanks for spotting this issue! We fixed these bugs, now UserName will not allow spaces and other valies will not be less then zero in Enatega's SingleVendor admin. 

@ninjas-code-official/ninjas-code
@beKashif

![username issue](https://github.com/ninjas-code-official/food-delivery-singlevendor/assets/87254179/fd64955f-de1f-42f8-a53a-1a96a6531769)
