### ISSUE TITLE
Error Opening Burger Section and Selecting Restaurants in Enatega SingleVendor Customer App

### ISSUE THREAD

**Issue by Inshirah23** [Ninjas-Code-official/Enatega-Food-Delivery-Solution#33]
**Describe the bug**
Users are encountering an error in the Enatega SingleVendor Customer App when attempting to open the section for burgers and selecting a restaurant. The application displays an error message, preventing users from accessing the desired restaurant options within the burger section.

**To Reproduce**
1. Open the Enatega SingleVendor Customer App.
2. Navigate to the section dedicated to burgers.
3. Attempt to select a specific restaurant within the burger section.

**Expected behavior**
Users should be able to browse the burger section and select a restaurant without encountering errors, providing a seamless and uninterrupted user experience.

**Screenshots**
https://github.com/ninjas-code-official/food-delivery-singlevendor/assets/152266796/ac1447c9-81d7-4598-9ba3-59660d2cdef3

**Smartphone:**
 - Device:  iPhone
 
**Additional context**
The issue seems to be specific to the burger section, as users have reported successful navigation in other sections.

**Comment by aliyanlatif** [comment]
This issue has been resolved.
