### ISSUE TITLE
 Language Localization Issue in Enatega SingleVendor Customer App - "Item Out of Stock" Tag

### ISSUE THREAD

**Issue by Inshirah23** [Ninjas-Code-official/Enatega-Food-Delivery-Solution#34]
**Describe the bug**
The Enatega SingleVendor Customer App is experiencing a language localization problem related to the "Item Out of Stock" tag. After changing the app language, the tag indicating that an item is out of stock is not being translated into the newly selected language. Instead, it continues to display in the app's previous language, leading to a discrepancy in language representation.

**To Reproduce**
1. Open the Enatega SingleVendor Customer App.
2. Change the app language to a language different from the default language.
3. Browse the app and encounter an item that is out of stock.

**Expected behavior**
The "Item Out of Stock" tag should be translated into the newly selected language, providing users with accurate and localized information about the item's availability.

**Screenshots**

https://github.com/ninjas-code-official/food-delivery-singlevendor/assets/152266796/71880221-a88f-49fb-a69b-d91e9ffd31c6

**Smartphone:**
 - Device: iPhone

**Additional context**
This issue specifically pertains to the translation of the "Item Out of Stock" tag.
Users have reported encountering this language localization problem consistently.

**Comment by Romana-Aijaz** [comment]
Resolved!
