### ISSUE TITLE
Inability to Change Language After Login in Enatega Single Vendor Admin Dashboard

### ISSUE THREAD

**Issue by Inshirah23** [Ninjas-Code-official/Enatega-Food-Delivery-Solution#35]
**Describe the bug**
Users of the Enatega Single Vendor Admin Dashboard are experiencing a limitation in language customization. The language can only be changed before logging in, and once logged in, there is no provision to modify the language settings.

**To Reproduce**
1. Open the Enatega Single Vendor Admin Dashboard.
2. Log in with valid credentials.
3. Navigate to the language settings or language dropdown.
4. Attempt to change the language after logging in.

**Expected behavior**
Users should be able to change the language settings within the Enatega Single Vendor Admin Dashboard both before and after logging in for a more flexible and personalized experience.

**Screenshots**
https://github.com/ninjas-code-official/food-delivery-singlevendor/assets/152266796/777cdfa4-cde3-45c7-b67c-cce5afb31652

**Desktop:**
 - Browser: chrome 

**Additional context**
Users should be able to change the language settings within the Enatega Single Vendor Admin Dashboard both before and after logging in for a more flexible and personalized experience.

**Comment by theKashif** [comment]
Hi @Inshirah23 

The Localisation drop-down has been successfully added by @Romana-Aijaz in the Navbar. This was causing a bad UX problem for users thanks for noticing this issue.

@ninjas-code-official/ninjas-code 
@beKashif 
![12-language in navbar](https://github.com/ninjas-code-official/food-delivery-singlevendor/assets/87254179/caff2988-b78c-4372-873f-7e16b2991646)
