### ISSUE TITLE
Language Placeholder Mismatch in "Reason If Reject" Field After Switching Language

### ISSUE THREAD

**Issue by Inshirah23** [Ninjas-Code-official/Enatega-Food-Delivery-Solution#36]
**Describe the bug**
In the Enatega Single Vendor Admin Dashboard, a language inconsistency is observed in the "Reason If Reject" field when switching the language. After changing the language, the placeholder text associated with the "Reason If Reject" field, which is located alongside the "Cancel Order" tag, does not update to reflect the new language.

**To Reproduce**
1. Open the Enatega Single Vendor Admin Dashboard.
2. Log in with valid credentials.
3. Switch the language within the dashboard settings.
4. Navigate to an order that requires acceptance or rejection.
5. Observe the "Reason If Reject" field alongside the "Cancel Order" tag.

**Expected behavior**
After switching the language, the placeholder text in the "Reason If Reject" field should dynamically update to match the selected language, providing a seamless and consistent user experience.

**Screenshots**
![image](https://github.com/ninjas-code-official/food-delivery-singlevendor/assets/152266796/eaaf995c-82d2-48c0-b37c-dc428491f887)

**Desktop:**
 - Browser chrome

**Additional context**
This issue affects language consistency and may lead to potential miscommunication in rejection reasons.

**Comment by theKashif** [comment]
Hi @Inshirah23,

The overall localization of this page has been successfully added and 'Reason is rejected' as well, thanks for spotting this issue, it was causing a bad inconsistency in language localization.

@ninjas-code-official/ninjas-code 
@beKashif 
![12-rejection text localisation](https://github.com/ninjas-code-official/food-delivery-singlevendor/assets/87254179/ce38e419-f707-45d7-9f2a-46293865c443)
