### ISSUE TITLE
Language Inconsistency in "Accept" or "Cancel Order" Tags After Switching Language 

### ISSUE THREAD

**Issue by Inshirah23** [Ninjas-Code-official/Enatega-Food-Delivery-Solution#37]
**Describe the bug**
A language inconsistency is observed in the Enatega Single Vendor Admin Dashboard, specifically in the "Orders" section. After switching the language within the dashboard settings, the labels associated with the "Accept Order" and "Cancel Order" tags do not dynamically update to reflect the new language.

**To Reproduce**
1. Open the Enatega Single Vendor Admin Dashboard.
2. Log in with valid credentials.
3. Switch the language within the dashboard settings.
4. Navigate to the "Orders" section.
5. Open any order to view the "Accept Order" and "Cancel Order" tags.

**Expected behavior**
After switching the language, the labels on the "Accept Order" and "Cancel Order" tags should dynamically update to match the selected language, ensuring a consistent and user-friendly experience.

**Screenshots**
![image](https://github.com/ninjas-code-official/food-delivery-singlevendor/assets/152266796/211d3289-ac70-4113-9347-f78756da49bc)

**Desktop:**
 - Browser: chrome

**Additional context**
This issue affects language consistency, which is crucial for clear communication in order management.

**Comment by theKashif** [comment]
Hi @Inshirah23,

The overall localization of this page has been successfully added, 'Accept' or 'Cancel Order' as well, thanks for spotting this issue, it was causing a bad inconsistency in language localization.

@ninjas-code-official/ninjas-code 
@beKashif 
![12-rejection text localisation](https://github.com/ninjas-code-official/food-delivery-singlevendor/assets/87254179/ce38e419-f707-45d7-9f2a-46293865c443)
