### ISSUE TITLE
 Pop-up Not Closing After Canceling Order

### ISSUE THREAD

**Issue by Inshirah23** [Ninjas-Code-official/Enatega-Food-Delivery-Solution#38]
**Describe the bug**
In the Enatega Single Vendor Admin Dashboard, there is a functional issue where the pop-up window associated with canceling an order does not close automatically after the cancellation process is completed.

**To Reproduce**
1. Open the Enatega Single Vendor Admin Dashboard.
2. Log in with valid credentials.
3. Navigate to the "Orders" section.
4. Open any order that needs to be canceled.
5. Initiate the cancellation process.
6. Observe the pop-up window that confirms the order cancellation.

**Expected behavior**
After confirming the order cancellation, the pop-up window should automatically close, providing a smooth and intuitive user experience.

**Screenshots**
https://github.com/ninjas-code-official/food-delivery-singlevendor/assets/152266796/18fbbb73-f7de-43be-b808-e2a6052ee6af

**Desktop:**
 - Browser: chrome

**Additional context**
This issue affects the overall user experience, particularly in the order management process.

**Comment by theKashif** [comment]
Hi @Inshirah23,

Thanks for spotting this issue, This feature has been added successfully, and now the popup will be closed on canceling the order, and also the order status will be changed as well.

@ninjas-code-official/ninjas-code
@beKashif
![12- popup will closed on canceling](https://github.com/ninjas-code-official/food-delivery-singlevendor/assets/87254179/790d7579-560b-4e4b-a3a1-cad16e8ef6d8)
