### ISSUE TITLE
Language Inconsistency in Order Details Section After Switching Language

### ISSUE THREAD

**Issue by Inshirah23** [Ninjas-Code-official/Enatega-Food-Delivery-Solution#39]
**Describe the bug**
Users of the Enatega Single Vendor Admin Dashboard are experiencing a language inconsistency when switching languages, particularly in the "Order Details" section. After changing the language within the dashboard settings, the content within the "Order Details" section does not dynamically update to reflect the new language.

**To Reproduce**
1. Open the Enatega Single Vendor Admin Dashboard.
2. Log in with valid credentials.
3. Switch the language within the dashboard settings.
4. Navigate to the "Orders" section.
5. Open any order to view the "Order Details" section

**Expected behavior**
After switching the language, the content within the "Order Details" section should dynamically update to match the selected language, providing a consistent and user-friendly experience.

**Screenshots**
![image](https://github.com/ninjas-code-official/food-delivery-singlevendor/assets/152266796/c6665d03-6017-4b5c-9d3d-1383f25a05b1)

**Desktop:**
 - Browser: chrome
 
**Additional context**
This issue impacts language consistency and may lead to potential misinterpretation of order details.

**Comment by theKashif** [comment]
Hi @Inshirah23,

The overall localization of this page has been successfully added, thanks for spotting this issue, it was causing a bad inconsistency in language localization.

@ninjas-code-official/ninjas-code
@beKashif
![12- order detail section](https://github.com/ninjas-code-official/food-delivery-singlevendor/assets/87254179/d012f54d-d51d-440f-8f77-2a60d1ccf556)
