### ISSUE TITLE
 Language Inconsistency in Placeholder Text After Switching Language 

### ISSUE THREAD

**Issue by Inshirah23** [Ninjas-Code-official/Enatega-Food-Delivery-Solution#40]
**Describe the bug**
A language inconsistency is observed in the Enatega Single Vendor Admin Dashboard, specifically in the "Riders" section. After switching the language within the dashboard settings, the placeholder text for input fields remains in English, creating a mismatch with the selected language.

**To Reproduce**
1. Open the Enatega Single Vendor Admin Dashboard.
2. Log in with valid credentials.
3. Switch the language within the dashboard settings.
4. Navigate to the "Riders" section.
5. Observe the placeholder text in input fields

**Expected behavior**
After switching the language, the placeholder text in input fields within the "Riders" section should dynamically update to match the selected language, providing a consistent and user-friendly experience.

**Screenshots**
![image](https://github.com/ninjas-code-official/food-delivery-singlevendor/assets/152266796/87d31723-336c-4cb8-acb2-21b6f941466b)

**Desktop:**
 - Browser: chrome

**Additional context**
This issue affects language consistency, particularly in critical sections such as "Riders" management.

**Comment by theKashif** [comment]
Hi @Inshirah23,

Thanks for finding this bug, it was causing inconsistency behavior in placeholder texts, and now it has been removed.

@ninjas-code-official/ninjas-code
@beKashif
![12- placeholder](https://github.com/ninjas-code-official/food-delivery-singlevendor/assets/87254179/78978cb5-51ff-4a08-8ad6-b35785a0d1b6)
