### ISSUE TITLE
Admin Panel Issue

### ISSUE THREAD

**Issue by ChristianBalibad** [Ninjas-Code-official/Enatega-Food-Delivery-Solution#9]
This is the full error when u open the admin panel:
TypeError: Cannot read properties of undefined (reading 'message')
onError
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/src/views/Login.jsx:139
  136 |     console.log('error', JSON.stringify(error));
  137 |     setEmailError(null);
  138 |     setPasswordError(null);
> 139 |     setError(error.graphQLErrors[0].message);
      | ^  140 |   }}
  141 | >
  142 |   {(adminLogin, { loading, error }) => {
View compiled
Mutation.callOnError
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/node_modules/react-apollo/react-apollo.esm.js:529
  526 | _this.onMutationError = function (error, mutationId) {
  527 |   var onError = _this.props.onError;
  528 |   var callOnError = function callOnError() {
> 529 |     return onError ? onError(error) : null;
      | ^  530 |   };
  531 |   if (_this.hasMounted && _this.isMostRecentMutation(mutationId)) {
  532 |     _this.setState({
View compiled
callCallback
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/node_modules/react-dom/cjs/react-dom.development.js:15204
  15201 | }
  15202 | function callCallback(callback, context) {
  15203 |   !(typeof callback === 'function') ? invariant(false, 'Invalid argument passed as callback. Expected a function. Instead received: %s', callback) : void 0;
> 15204 |   callback.call(context);
        | ^  15205 | }
  15206 | function resetHasForceUpdateBeforeProcessing() {
  15207 |   hasForceUpdate = false;
View compiled
commitUpdateEffects
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/node_modules/react-dom/cjs/react-dom.development.js:15238
  15235 |   var _callback3 = effect.callback;
  15236 |   if (_callback3 !== null) {
  15237 |     effect.callback = null;
> 15238 |     callCallback(_callback3, instance);
        | ^  15239 |   }
  15240 |   effect = effect.nextEffect;
  15241 | }
View compiled
commitUpdateQueue
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/node_modules/react-dom/cjs/react-dom.development.js:15228
  15225 | }
  15226 | 
  15227 | // Commit the effects
> 15228 | commitUpdateEffects(finishedQueue.firstEffect, instance);
        | ^  15229 | finishedQueue.firstEffect = finishedQueue.lastEffect = null;
  15230 | commitUpdateEffects(finishedQueue.firstCapturedEffect, instance);
  15231 | finishedQueue.firstCapturedEffect = finishedQueue.lastCapturedEffect = null;
View compiled
commitLifeCycles
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/node_modules/react-dom/cjs/react-dom.development.js:16098
  16095 |     // We could update instance props and state here,
  16096 |     // but instead we rely on them being set during last render.
  16097 |     // TODO: revisit this when we implement resuming.
> 16098 |     commitUpdateQueue(finishedWork, updateQueue, instance, committedExpirationTime);
        | ^  16099 |   }
  16100 |   return;
  16101 | }
View compiled
commitAllLifeCycles
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/node_modules/react-dom/cjs/react-dom.development.js:17401
  17398 | if (effectTag & (Update | Callback)) {
  17399 |   recordEffect();
  17400 |   var current$$1 = nextEffect.alternate;
> 17401 |   commitLifeCycles(finishedRoot, current$$1, nextEffect, committedExpirationTime);
        | ^  17402 | }
  17403 | if (effectTag & Ref) {
  17404 |   recordEffect();
View compiled
HTMLUnknownElement.callCallback
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/node_modules/react-dom/cjs/react-dom.development.js:139
  136 |   if (typeof window.event !== 'undefined' && window.hasOwnProperty('event')) {
  137 |     window.event = windowEvent;
  138 |   }
> 139 |   func.apply(context, funcArgs);
      | ^  140 |   didError = false;
  141 | }
  142 | 
View compiled
invokeGuardedCallbackDev
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/node_modules/react-dom/cjs/react-dom.development.js:188
  185 | // Synchronously dispatch our fake event. If the user-provided function
  186 | // errors, it will trigger our global error handler.
  187 | evt.initEvent(evtType, false, false);
> 188 | fakeNode.dispatchEvent(evt);
      | ^  189 | if (windowEventDescriptor) {
  190 |   Object.defineProperty(window, 'event', windowEventDescriptor);
  191 | }
View compiled
invokeGuardedCallback
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/node_modules/react-dom/cjs/react-dom.development.js:240
  237 | function invokeGuardedCallback(name, func, context, a, b, c, d, e, f) {
  238 |   hasError = false;
  239 |   caughtError = null;
> 240 |   invokeGuardedCallbackImpl$1.apply(reporter, arguments);
      | ^  241 | }
  242 | 
  243 | /**
View compiled
commitRoot
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/node_modules/react-dom/cjs/react-dom.development.js:17596
  17593 | var _didError2 = false;
  17594 | var _error2 = void 0;
  17595 | {
> 17596 |   invokeGuardedCallback(null, commitAllLifeCycles, null, root, committedExpirationTime);
        | ^  17597 |   if (hasCaughtError()) {
  17598 |     _didError2 = true;
  17599 |     _error2 = clearCaughtError();
View compiled
(anonymous function)
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/node_modules/react-dom/cjs/react-dom.development.js:18966
  18963 |     nestedUpdateCount = 0;
  18964 |   }
  18965 |   scheduler.unstable_runWithPriority(scheduler.unstable_ImmediatePriority, function () {
> 18966 |     commitRoot(root, finishedWork);
        | ^  18967 |   });
  18968 | }
  18969 | function onUncaughtError(error) {
View compiled
unstable_runWithPriority
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/node_modules/scheduler/cjs/scheduler.development.js:239
  236 | currentPriorityLevel = priorityLevel;
  237 | currentEventStartTime = exports.unstable_now();
  238 | try {
> 239 |   return eventHandler();
      | ^  240 | } finally {
  241 |   currentPriorityLevel = previousPriorityLevel;
  242 |   currentEventStartTime = previousEventStartTime;
View compiled
completeRoot
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/node_modules/react-dom/cjs/react-dom.development.js:18965
  18962 |     lastCommittedRootDuringThisBatch = root;
  18963 |     nestedUpdateCount = 0;
  18964 |   }
> 18965 |   scheduler.unstable_runWithPriority(scheduler.unstable_ImmediatePriority, function () {
        | ^  18966 |     commitRoot(root, finishedWork);
  18967 |   });
  18968 | }
View compiled
performWorkOnRoot
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/node_modules/react-dom/cjs/react-dom.development.js:18896
  18893 |     finishedWork = root.finishedWork;
  18894 |     if (finishedWork !== null) {
  18895 |       // We've completed the root. Commit it.
> 18896 |       completeRoot(root, finishedWork, expirationTime);
        | ^  18897 |     }
  18898 |   }
  18899 | } else {
View compiled
performWork
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/node_modules/react-dom/cjs/react-dom.development.js:18810
  18807 |   }
  18808 | } else {
  18809 |   while (nextFlushedRoot !== null && nextFlushedExpirationTime !== NoWork && minExpirationTime <= nextFlushedExpirationTime) {
> 18810 |     performWorkOnRoot(nextFlushedRoot, nextFlushedExpirationTime, false);
        | ^  18811 |     findHighestPriorityRoot();
  18812 |   }
  18813 | }
View compiled
performSyncWork
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/node_modules/react-dom/cjs/react-dom.development.js:18788
  18785 |   }
  18786 | }
  18787 | function performSyncWork() {
> 18788 |   performWork(Sync, false);
        | ^  18789 | }
  18790 | function performWork(minExpirationTime, isYieldy) {
  18791 |   // Keep working on roots until there's no more work, or until there's a higher
View compiled
requestWork
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/node_modules/react-dom/cjs/react-dom.development.js:18662
  18659 | 
  18660 | // TODO: Get rid of Sync and use current time?
  18661 | if (expirationTime === Sync) {
> 18662 |   performSyncWork();
        | ^  18663 | } else {
  18664 |   scheduleCallbackWithExpirationTime(root, expirationTime);
  18665 | }
View compiled
scheduleWork
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/node_modules/react-dom/cjs/react-dom.development.js:18489
  18486 | // ...unless this is a different root than the one we're rendering.
  18487 | nextRoot !== root) {
  18488 |   var rootExpirationTime = root.expirationTime;
> 18489 |   requestWork(root, rootExpirationTime);
        | ^  18490 | }
  18491 | if (nestedUpdateCount > NESTED_UPDATE_LIMIT) {
  18492 |   // Reset this back to zero so subsequent updates don't throw.
View compiled
enqueueSetState
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/node_modules/react-dom/cjs/react-dom.development.js:10369
  10366 |   }
  10367 |   flushPassiveEffects();
  10368 |   enqueueUpdate(fiber, update);
> 10369 |   scheduleWork(fiber, expirationTime);
        | ^  10370 | },
  10371 | enqueueReplaceState: function enqueueReplaceState(inst, payload, callback) {
  10372 |   var fiber = get(inst);
View compiled
push../node_modules/react/cjs/react.development.js.Component.setState
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/node_modules/react/cjs/react.development.js:310
  307 |  */
  308 | Component.prototype.setState = function (partialState, callback) {
  309 |   !(typeof partialState === 'object' || typeof partialState === 'function' || partialState == null) ? invariant(false, 'setState(...): takes an object of state variables to update or a function which returns an object of state variables.') : void 0;
> 310 |   this.updater.enqueueSetState(this, partialState, callback, 'setState');
      | ^  311 | };
  312 | 
  313 | /**
View compiled
Mutation._this.onMutationError
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/node_modules/react-apollo/react-apollo.esm.js:532
  529 |   return onError ? onError(error) : null;
  530 | };
  531 | if (_this.hasMounted && _this.isMostRecentMutation(mutationId)) {
> 532 |   _this.setState({
      | ^  533 |     loading: false,
  534 |     error: error
  535 |   }, callOnError);
View compiled
(anonymous function)
C:/Users/kcrey/OneDrive/Documents/OnBites Foods/Admin Dashboard/node_modules/react-apollo/react-apollo.esm.js:457
  454 |     _this.onMutationCompleted(response, mutationId);
  455 |     return response;
  456 |   }).catch(function (e) {
> 457 |     _this.onMutationError(e, mutationId);
      | ^  458 |     if (!_this.props.onError) throw e;
  459 |   });
  460 | };
View compiled

![image](https://github.com/Ninjas-Code-official/Enatega-Restaurant-Solution/assets/133922808/885f5116-fb37-4968-ae7e-ae1369ab8932)
 @@

It won't redirect to the dashboard of the panel, any ways to fix this? I've tried what I can.

**Comment by ChristianBalibad** [comment]
UPDATE!

The official documentation of the admin dashboard is now working but this is the error i got when i opened it.

![image](https://github.com/Ninjas-Code-official/Enatega-Restaurant-Solution/assets/133922808/f4293ffb-46e1-4bca-91e6-c0698ac20d94)

This is the order section of the documentation admin dashboard

**Comment by ChristianBalibad** [comment]
Another Issue Regarding the Rider App, heres to full log:

AsyncStorage has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-async-storage/async-storage' instead of 'react-native'. See https://github.com/react-native-async-storage/async-storage
at node_modules\react-native\Libraries\Utilities\warnOnce.js:null in warnOnce
at node_modules\react-native\index.js:null in module.exports.get__AsyncStorage
at i18n.js:null in initAsync
at node_modules\@babel\runtime\helpers\asyncToGenerator.js:null in asyncGeneratorStep
at node_modules\@babel\runtime\helpers\asyncToGenerator.js:null in _next
at node_modules\@babel\runtime\helpers\asyncToGenerator.js:null in Promise$argument_0
at node_modules\react-native\node_modules\promise\setimmediate\core.js:null in tryCallTwo
at node_modules\react-native\node_modules\promise\setimmediate\core.js:null in doResolve
at node_modules\react-native\node_modules\promise\setimmediate\core.js:null in Promise
at node_modules\@babel\runtime\helpers\asyncToGenerator.js:null in <anonymous>
at App.js:null in loadData
at node_modules\@babel\runtime\helpers\asyncToGenerator.js:null in asyncGeneratorStep
at node_modules\@babel\runtime\helpers\asyncToGenerator.js:null in _next
at node_modules\@babel\runtime\helpers\asyncToGenerator.js:null in Promise$argument_0
at node_modules\react-native\node_modules\promise\setimmediate\core.js:null in tryCallTwo
at node_modules\react-native\node_modules\promise\setimmediate\core.js:null in doResolve
at node_modules\react-native\node_modules\promise\setimmediate\core.js:null in Promise
at node_modules\@babel\runtime\helpers\asyncToGenerator.js:null in <anonymous>
at App.js:null in App
at App.js:null in loadData
at App.js:null in useEffect$argument_0
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in commitHookEffectListMount
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in commitPassiveMountOnFiber
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in commitPassiveMountEffects_complete
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in commitPassiveMountEffects_begin
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in commitPassiveMountEffects
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in flushPassiveEffectsImpl
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in flushPassiveEffects
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in performSyncWorkOnRoot
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in flushSyncCallbacks
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in flushSyncCallbacksOnlyInLegacyMode
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in scheduleUpdateOnFiber
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in updateContainer
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in render
at node_modules\react-native\Libraries\ReactNative\renderApplication.js:null in renderApplication
at node_modules\react-native\Libraries\ReactNative\AppRegistry.js:null in runnables.appKey.run
at node_modules\react-native\Libraries\ReactNative\AppRegistry.js:null in runApplication
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in __callFunction
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in callFunctionReturnFlushedQueue

Warning: Internal React error: Attempted to capture a commit phase error inside a detached tree. This indicates a bug in React. Likely causes include deleting the same fiber more than once, committing an already-finished tree, or an inconsistent return pointer.

Error message:

%s%s, TypeError: _reactNative.Dimensions.removeEventListener is not a function. (In '_reactNative.Dimensions.removeEventListener('change', onChange)', '_reactNative.Dimensions.removeEventListener' is undefined), 
    in DrawerView (created by DrawerNavigator)
    in DrawerNavigator (created by Main)
    in UserProvider (created by Main)
    in Main (created by AppContainer)
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in printWarning
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in error
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in captureCommitPhaseError
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in safelyCallDestroy
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in commitHookEffectListUnmount
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in commitPassiveUnmountInsideDeletedTreeOnFiber
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in commitPassiveUnmountEffectsInsideOfDeletedTree_begin
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in commitPassiveUnmountEffects_begin
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in commitPassiveUnmountEffects
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in flushPassiveEffectsImpl
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in flushPassiveEffects
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in scheduleCallback$1$argument_1
at node_modules\scheduler\cjs\scheduler.development.js:null in workLoop
at node_modules\scheduler\cjs\scheduler.development.js:null in flushWork
at node_modules\scheduler\cjs\scheduler.development.js:null in performWorkUntilDeadline
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:null in _allocateCallback$argument_0
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:null in _callTimer
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:null in _callReactNativeMicrotasksPass
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:null in callReactNativeMicrotasks
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in __callReactNativeMicrotasks
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:null in flushedQueue

**Comment by MuhammadAdnan111** [comment]
We are glad to inform you that we have fixed the problem, and the admin dashboard is now working as intended.

Regarding the error you mentioned specifically in the order section returning null, I have also addressed this issue. Now, when you open the order section, it should no longer return null. You should be able to access and view the order information without any problems.

We appreciate your patience and understanding while we resolved these issues. If you encounter any further problems or have any additional questions, please don't hesitate to reach out to me. We are here to help.
Additionally, We wanted to inform you that we are currently working on fixing the rider app problem as well. We will get back to you as soon as we have an update or a solution.

Once again, thank you for bringing the issue to our attention, and have a great day!

**Comment by ChristianBalibad** [comment]
Thank you! Have a great day as well

**Comment by ChristianBalibad** [comment]
Where I can buy this so I can delete some products

**Comment by SharanGoharKhan** [comment]
@Keithsukei you need to contact sales@ninjascode.com for that
